-- Migration note for QR code images in payment_methods
-- Since payment_methods is a JSONB column inside raffle_config,
-- QR images are stored as base64 data URLs in the qrImageBase64 field.
-- No additional database schema changes are required.